"""add trade and user new columns

Revision ID: 6d447bdaba16
Revises: fabe11a477ac
Create Date: 2026-02-17 23:04:39.586500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d447bdaba16'
down_revision: Union[str, Sequence[str], None] = 'fabe11a477ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('stop_loss', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('take_profit', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('status', sa.String(), nullable=True))
    op.add_column('trades', sa.Column('exit_price', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('pnl', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('balance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'balance')
    op.drop_column('trades', 'pnl')
    op.drop_column('trades', 'exit_price')
    op.drop_column('trades', 'status')
    op.drop_column('trades', 'take_profit')
    op.drop_column('trades', 'stop_loss')
    # ### end Alembic commands ###
